#!/bin/vbash
# Include VyOS function calls
source /opt/vyatta/etc/functions/script-template
configure

set container name elasticsearch description 'Elastic database used to consolidate log sources, and data analytics for CLARA'
set container name elasticsearch entrypoint '/usr/share/elasticsearch/startup/setup-elastic.sh'
set container name elasticsearch environment ES_SETTING_DISCOVERY_TYPE value 'single-node'
set container name elasticsearch environment ES_SETTING_XPACK_MONITORING_COLLECTION_ENABLED value 'true'
set container name elasticsearch image 'docker.elastic.co/elasticsearch/elasticsearch:9.1.2'
set container name elasticsearch memory '6144'
set container name elasticsearch network elastic address '10.199.10.10'
set container name elasticsearch port 9200 destination '9200'
set container name elasticsearch port 9200 source '9200'
set container name elasticsearch volume config destination '/usr/share/elasticsearch/config'
set container name elasticsearch volume config source '/opt/elastic/config'
set container name elasticsearch volume data destination '/usr/share/elasticsearch/data'
set container name elasticsearch volume data source '/opt/elastic/data'
set container name elasticsearch volume enrollment destination '/usr/share/elasticsearch/enrollment'
set container name elasticsearch volume enrollment source '/opt/elastic/enrollment'
set container name elasticsearch volume logs destination '/usr/share/elasticsearch/logs'
set container name elasticsearch volume logs source '/opt/elastic/logs'
set container name elasticsearch volume plugins destination '/usr/share/elasticsearch/plugins'
set container name elasticsearch volume plugins source '/opt/elastic/plugins'
set container name elasticsearch volume startup destination '/usr/share/elasticsearch/startup'
set container name elasticsearch volume startup mode 'ro'
set container name elasticsearch volume startup source '/opt/clara/elastic/boot'
set container name fleet description 'Fleet Server: Used for log collection'
set container name fleet entrypoint '/usr/share/elastic-agent/startup/setup-fleet.sh'
set container name fleet environment ELASTICSEARCH_CA value '/usr/share/elastic-agent/certs/http_ca.crt'
set container name fleet environment FLEET_SERVER_ELASTICSEARCH_HOST value 'https://elasticsearch:9200'
set container name fleet environment FLEET_SERVER_ENABLE value 'true'
set container name fleet environment FLEET_SERVER_POLICY_ID value 'fleet-server-policy'
set container name fleet image 'docker.elastic.co/elastic-agent/elastic-agent:9.1.2'
set container name fleet memory '1024'
set container name fleet network elastic
set container name fleet port 2055 destination '2055'
set container name fleet port 2055 source '2055'
set container name fleet port 8220 destination '8220'
set container name fleet port 8220 source '8220'
set container name fleet volume certs destination '/usr/share/elastic-agent/certs'
set container name fleet volume certs mode 'ro'
set container name fleet volume certs source '/opt/elastic/config/certs'
set container name fleet volume enrollment destination '/usr/share/elastic-agent/enrollment'
set container name fleet volume enrollment mode 'ro'
set container name fleet volume enrollment source '/opt/elastic/enrollment'
set container name fleet volume startup destination '/usr/share/elastic-agent/startup'
set container name fleet volume startup mode 'ro'
set container name fleet volume startup source '/opt/clara/elastic/boot'
set container name kibana command '/usr/share/kibana/startup/setup-kibana.sh'
set container name kibana description 'Dashboard for Elastic - available for advanced users'
set container name kibana image 'docker.elastic.co/kibana/kibana:9.1.2'
set container name kibana memory '1024'
set container name kibana network elastic
set container name kibana port 5601 destination '5601'
set container name kibana port 5601 source '5601'
set container name kibana volume config destination '/usr/share/kibana/config'
set container name kibana volume config source '/opt/kibana/config'
set container name kibana volume data destination '/usr/share/kibana/data'
set container name kibana volume data source '/opt/kibana/data'
set container name kibana volume enrollment destination '/usr/share/kibana/enrollment'
set container name kibana volume enrollment source '/opt/elastic/enrollment'
set container name kibana volume logs destination '/usr/share/kibana/logs'
set container name kibana volume logs source '/opt/kibana/logs'
set container name kibana volume plugins destination '/usr/share/kibana/plugins'
set container name kibana volume plugins source '/opt/kibana/plugins'
set container name kibana volume startup destination '/usr/share/kibana/startup'
set container name kibana volume startup mode 'ro'
set container name kibana volume startup source '/opt/clara/elastic/boot'
set container network elastic description 'Container network Elastic Stack'
set container network elastic prefix '10.199.10.0/24'